spring:
  application:
    name: biointerface_server
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        types:
          print:
            banner: false
        default_schema: main_service
        ddl-auto: validate
        charset: UTF-8
        character_encoding: UTF-8
        use_unicode: true
        autocommit: false
        format_sql: true
        cache:
          use_second_level_cache: false
          provider_class: org.hibernate.cache.NoCacheProvider
  sql:
    init:
      encoding: UTF-8
  flyway:
    schemas: main_service
    ignore-missing-migrations: true
    table: flyway_history

  thymeleaf:
    prefix: "/WEB-INF/templates/"
    suffix: ".html"
    encoding: utf-8
    cache: false

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    ru.gsa.biointerface: DEBUG


