spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/biointerface"
    username: postgres
    password: postgres

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate
        charset: UTF-8
        character_encoding: UTF-8
        use_unicode: true
        autocommit: false
        format_sql: true
        cache:
          use_second_level_cache: false
          provider_class: org.hibernate.cache.NoCacheProvider

  thymeleaf:
    prefix: "/WEB-INF/templates/"
    suffix: ".html"
    encoding: utf-8
    cache: false
#
#logging:
#  level:
#    root: INFO
#    org.springframework.web: ERROR
#    com.howtodoinjava: DEBUG
#    org.hibernate: ERROR
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}%highlight{[%-5level]}%style{[%-20.20t]}{magenta}%style{%-35.35C{1.}:}{cyan}%msg%n"
#    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
#  file:
#    name: logs/today.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: logs/%d{yyyy-MM-dd}.log
#      max-history: 1

server:
  port: 8080