spring:
  application:
    name: biointerface_server
  profiles:
    active: dev
  sql:
    init:
      encoding: UTF-8
  flyway:
    schemas: main_service
    ignore-missing-migrations: true
    table: flyway_history
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        types:
          print:
            banner: false
        default_schema: main_service
        ddl-auto: validate
        charset: UTF-8
        character_encoding: UTF-8
        use_unicode: true
        autocommit: false
        format_sql: true
        cache:
          use_second_level_cache: false
          provider_class: org.hibernate.cache.NoCacheProvider

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: always


