spring:
  application:
    name: biointerface_server
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: false
  sql:
    init:
      encoding: UTF-8
  flyway:
    schemas: default
    ignore-missing-migrations: true
    table: flyway_schema_history

  thymeleaf:
    prefix: "/WEB-INF/templates/"
    suffix: ".html"
    encoding: utf-8
    cache: false

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: "Europe/Moscow"
    serialization:
      write_dates_as_timestamps: false

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    ru.gsa.biointerface: DEBUG


