spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biointerface
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  sql:
    init:
      platform: postgres
      encoding: UTF-8
  flyway:
    schemas: main_service
    ignore-missing-migrations: true
    table: flyway_history
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        types:
          print:
            banner: false
        default_schema: main_service
        ddl-auto: validate
        charset: UTF-8
        character_encoding: UTF-8
        use_unicode: true
        autocommit: false
        format_sql: true
        cache:
          use_second_level_cache: false
          provider_class: org.hibernate.cache.NoCacheProvider
  thymeleaf:
    prefix: "/WEB-INF/templates/"
    suffix: ".html"
    encoding: utf-8
    cache: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    ru.gsa.biointerface: INFO